---
# Service Account for the Events API
apiVersion: v1
kind: ServiceAccount
metadata:
  name: events-api
  namespace: events-app
  labels:
    app: events-api

---
# Service Account for the Events Web UI
apiVersion: v1
kind: ServiceAccount
metadata:
  name: events-web
  namespace: events-app
  labels:
    app: events-web
